function methodStr = fillDynamicTableMethods()
methodStr = strjoin({...
    'function addRow(obj, varargin)',...
    '    matnwb.types.util.dynamictable.addRow(obj, varargin{:});',...
    'end',...
    '',...
    'function addColumn(obj, varargin)',...
    '    matnwb.types.util.dynamictable.addColumn(obj, varargin{:});',...
    'end',...
    '',...
    'function row = getRow(obj, id, varargin)',...
    '    row = matnwb.types.util.dynamictable.getRow(obj, id, varargin{:});',...
    'end',...
    '',...
    'function table = toTable(obj, varargin)',...
    '    table = matnwb.types.util.dynamictable.nwbToTable(obj, varargin{:});',...
    'end',...
    '',...
    'function clear(obj)',...
    '    matnwb.types.util.dynamictable.clear(obj);',...
    'end'}, newline);
end

