# Run MATLAB tests across multiple MATLAB versions and create a draft release

name: Prepare release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in major.minor.patch format, i.e 2.8.0'
        required: true
        type: string

jobs:
  validate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check version format
        run: |
          version="${{ github.event.inputs.version }}"
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Input for 'version' ('$version') is not in the expected major.minor.patch format."
            exit 1
          fi
          echo "Version '$version' is valid."

  run_tests:
    name: Run MATLAB tests (${{ matrix.matlab-version }})
    runs-on: ubuntu-latest
    needs: [validate_version]
    strategy:
      fail-fast: false
      matrix:
        include:
          - matlab-version: R2021a
            python-version: '3.9'
            skip-pynwb-compatibilty-test-for-tutorial: '1'
          - matlab-version: R2021b
            python-version: '3.9'
            skip-pynwb-compatibilty-test-for-tutorial: '1'
          - matlab-version: R2022a
            python-version: '3.9'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
          - matlab-version: R2022b
            python-version: '3.9'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
          - matlab-version: R2023a
            python-version: '3.10'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
          - matlab-version: R2023b
            python-version: '3.10'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
          - matlab-version: R2024a
            python-version: '3.11'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
          - matlab-version: R2024b
            python-version: '3.11'
            skip-pynwb-compatibilty-test-for-tutorial: '0'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure python env
        run: |
          python -m pip install -U pip
          pip install -r +tests/requirements.txt
          python -m pip list
          echo "HDF5_PLUGIN_PATH=$(python -c "import hdf5plugin; print(hdf5plugin.PLUGINS_PATH)")" >> "$GITHUB_ENV"
          echo $( python -m pip show nwbinspector | grep ^Location: | awk '{print $2}' )

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-version }}

      - name: Run tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            setenv("SKIP_PYNWB_COMPATIBILITY_TEST_FOR_TUTORIALS", ...
                num2str(${{ matrix.skip-pynwb-compatibilty-test-for-tutorial }}))
            pyenv("ExecutionMode", "OutOfProcess");
            results = assertSuccess(nwbtest('ReportOutputFolder', '.')); 
            assert(~isempty(results), 'No tests ran');

      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.matlab-version }}
          path: testResults.xml

  publish_junit:
    name: Publish JUnit test results
    runs-on: ubuntu-latest
    needs: [run_tests]
    if: always()
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Retrieve result files
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          merge-multiple: true

      - name: Publish test results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'testResults*.xml'

  update_version:
    name: Create new draft relase for given version
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Tag repository with version tag
        if: always()
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"

          # Recreate the tag with a message, including [skip ci] to prevent CI workflows
          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}" 

          # Push the new tag to the remote repository
          git push origin "${{ inputs.version }}"

      - name: Update Contents.m file
        run: |
          # Read the template file
          template=$(cat .github/workflows/templates/contents_header_template.txt)
          
          # Get current date in DD-MMM-YYYY format
          date_string=$(date +"%d-%b-%Y")
          
          # Get current year
          year_number=$(date +"%Y")
          
          # Replace placeholders in template
          header="${template/\{\{version_number\}\}/${{ github.event.inputs.version }}}"
          header="${header/\{\{date_string\}\}/$date_string}"
          header="${header/\{\{year_number\}\}/$year_number}"
          
          # Extract the content after the header from the current Contents.m file
          content=$(awk '/^% -{10,}/{flag=1;next} flag{print}' Contents.m)
          
          # Combine new header with existing content
          echo "$header" > Contents.m
          echo "$content" >> Contents.m

      - name: Commit updated Contents.m file
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"
          git add Contents.m
          git commit -m "Update version number in Contents.m"
          git fetch
          git push

      #- name: Generate tested with badge
      #  # TODO

      - name: Push to gh-badges
        run: |
          mkdir -p gh-badges/.github/badges/${{  github.ref_name }}
          cp .github/badges/${{  github.ref_name }}/tested_with.json gh-badges/.github/badges/${{  github.ref_name }}/tested_with.json
          cd gh-badges

          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"

          # Only proceed with commit and push if changes are detected
          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update tested with badge for release"
            git push -f
          else
            echo "Nothing to commit"
          fi

      # Create the release
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          draft: true        
          generateReleaseNotes: true
          body: "![MATLAB Versions Tested](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Fehennestad%2Fmatnwb%2Fgh-badges%2F.github%2Fbadges%2F$v{{ inputs.version }}%2Ftested_with.json)"
